name: CI/CD Pipeline for GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

      #steps 2 
    - name: Save GCP Service Account Key
      run: |
        echo "${{ secrets._GKE_GO_API_SERVICE_ACCOUNT }}" > gcp-key.json

    - name: Debug GCP_SA_KEY Content
      run: |
        echo "Secret content:"
        echo "${{ secrets._GKE_GO_API_SERVICE_ACCOUNT }}"

    # Step 4: Authenticate with GCP
    - name: Authenticate with GCP
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
      run: |
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project gcp-go-tutorial-444621

    # Step 5: Deploy to GKE
    - name: Deploy to GKE Dev Cluster
      run: |
        kubectl config use-context gke-dev-cluster
        kubectl set image deployment/go-api-deployment go-api=us-east1-docker.pkg.dev/gcp-go-tutorial-444621/go-api-docker-repo/go-api:${{ github.sha }}
