name: CI/CD Pipeline for GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Authenticate with GCP and Setup gcloud
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets._GKE_GO_API_SERVICE_ACCOUNT }}

    - name: Set Up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: "latest"
        install_components: 'gke-gcloud-auth-plugin'

      ### Configure Docker for Artifact Registry ###
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-east1-docker.pkg.dev

      ### Build Docker Image ###
    - name: Build Docker Image
      run: |
          docker build -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/go-api-docker-repo/go-api:${{ github.sha }} .

      ### Push Docker Image to Artifact Registry ###
    - name: Push Docker Image
      run: |
          docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/go-api-docker-repo/go-api:${{ github.sha }}


    # Step 3: Get GKE Cluster Credentials
    - name: Get GKE Cluster Credentials
      run: |
        gcloud container clusters get-credentials gke-dev-cluster \
          --region us-east1 \
          --project gcp-go-tutorial-444621

    # Step 4: Deploy to GKE
    - name: Deploy to GKE Dev Cluster
      run: |
        kubectl set image deployment/go-api-deployment \
          go-api=us-east1-docker.pkg.dev/gcp-go-tutorial-444621/go-api-docker-repo/go-api:${{ github.sha }}