name: CI/CD Pipeline for GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Save GCP Service Account Key
      run: |
        echo "${{ secrets._GKE_GO_API_SERVICE_ACCOUNT }}" | base64 --decode > gcp-key.json
        cat gcp-key.json | jq . # Verify JSON structure

    - name: Debug GCP_SA_KEY Content
      run: |
        echo "Secret content:"
        echo "${{ secrets._GKE_GO_API_SERVICE_ACCOUNT }}"

    # Step 4: Authenticate with GCP
    - name: Authenticate with GCP
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
      run: |
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project gcp-go-tutorial-444621

    - name: Get GKE cluster creds
      run: |
        gcloud container clusters get-credentials gke-dev-cluster \
        --region us-east1 \
        --project gcp-go-tutorial-444621

    - name: Install gke-gcloud-auth-plugin
      run: |
          curl -LO https://packages.cloud.google.com/apt/doc/apt-key.gpg
          sudo apt-key add apt-key.gpg
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    # Step 5: Deploy to GKE
    - name: Deploy to GKE Dev Cluster
      run: |
        kubectl set image deployment/go-api-deployment go-api=us-east1-docker.pkg.dev/gcp-go-tutorial-444621/go-api-docker-repo/go-api:${{ github.sha }}
